name: Detect Severity Label Change

on:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  issues: write

jobs:
  detect-severity-change:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Debug event payload
      run: cat $GITHUB_EVENT_PATH

    - name: Check severity label addition or removal
      id: check-label
      run: |
        set -euxo pipefail

        # Fetch the event payload
        payload=$(cat $GITHUB_EVENT_PATH)

        # Extract the label being added or removed
        label_name=$(echo "$payload" | jq -r '.label.name // empty')

        # Define severity labels
        severity_labels=("Severity-1" "Severity-2" "Severity-3" "Severity-4")

        # Initialize variable
        notify=false

        # Check if the label is a severity label
        if [[ " ${severity_labels[@]} " =~ " $label_name " ]]; then
          notify=true
        fi

        # Output result
        echo "notify=$notify" >> $GITHUB_ENV
        echo "label_name=$label_name" >> $GITHUB_ENV

    - name: Notify user on severity label change (addition or removal)
      if: env.notify == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "labeled" ]]; then
          gh issue comment ${{ github.event.issue.number }} --body "Attention @QuamrulSiddiqui, the **$label_name** severity label has been **added** to this issue! Please update the same in the project board"
        elif [[ "$GITHUB_EVENT_NAME" == "unlabeled" ]]; then
          gh issue comment ${{ github.event.issue.number }} --body "Attention @QuamrulSiddiqui, the **$label_name** severity label has been **removed** from this issue! Please update the same in the project board"
        fi
