name: Detect Severity Label Change

on:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  issues: write

jobs:
  detect-severity-change:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Debug event payload
      run: cat $GITHUB_EVENT_PATH

    - name: Check for severity label changes
      id: check-label
      run: |
        set -euxo pipefail

        # Fetch the event payload
        payload=$(cat $GITHUB_EVENT_PATH)

        # Extract current and previous labels safely
        previous_labels=$(echo "$payload" | jq -r '.changes.labels.from[]?.name // empty')
        current_labels=$(echo "$payload" | jq -r '.issue.labels[].name // empty')

        # Define severity labels
        severity_labels=("Severity-1" "Severity-2" "Severity-3" "Severity-4")

        # Initialize variables
        severity_added=false
        severity_removed=false

        # Check if any severity label was added or removed
        for label in "${severity_labels[@]}"; do
          if [[ ! "$previous_labels" =~ $label && "$current_labels" =~ $label ]]; then
            severity_added=true
          elif [[ "$previous_labels" =~ $label && ! "$current_labels" =~ $label ]]; then
            severity_removed=true
          fi
        done

        # Output results
        echo "severity_added=$severity_added" >> $GITHUB_ENV
        echo "severity_removed=$severity_removed" >> $GITHUB_ENV

    - name: Debugging Logs
      run: |
        echo "Previous Labels: $previous_labels"
        echo "Current Labels: $current_labels"

    - name: Notify user on severity label addition
      if: env.severity_added == 'true'|| env.severity_removed == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue comment ${{ github.event.issue.number }} --body "Attention @QuamrulSiddiqui, a severity label has been **Updated** to this issue! Please update the same in the project board"

