name: Detect Severity Label Change

on:
  issues:
    types:
      - edited

jobs:
  detect-severity-change:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Check for severity label changes
      id: check-label
      run: |
        # Fetch the event payload
        payload=$(cat $GITHUB_EVENT_PATH)
        
        # Extract current and previous labels
        previous_labels=$(echo "$payload" | jq -r '.changes.labels.from[]?.name')
        current_labels=$(echo "$payload" | jq -r '.issue.labels[].name')
        
        # Define severity labels
        severity_labels=("Severity-1" "Severity-2" "Severity-3" "Severity-4")
        
        # Check if any severity label changed
        severity_changed=false
        for label in "${severity_labels[@]}"; do
          if [[ "$previous_labels" =~ $label && ! "$current_labels" =~ $label ]]; then
            severity_changed=true
            break
          elif [[ ! "$previous_labels" =~ $label && "$current_labels" =~ $label ]]; then
            severity_changed=true
            break
          fi
        done
        
        echo "severity_changed=$severity_changed" >> $GITHUB_ENV

    - name: Notify user
      if: env.severity_changed == 'true'
      run: |
        gh issue comment ${{ github.event.issue.number }} --body "Attention @QuamrulSiddiqui, the severity of this issue has changed! please update the same in the project board"
